title: Yeray Ruiz Portfolio
description: My personal portfolio showcasing projects and skills
theme: jekyll-theme-cayman

# Opcional:
author: Yeray Ruiz Suarez
email: yeray.r7@gmail.com
url: "https://yerayruizsuarez.github.io"
